---
- name: Install and start the nginx service
  hosts: localhost
  
  tasks:
  - name: install nginx
    apt-get:      
      name: nginx
      state: present
  - name: start nginx
      service:
        name: nginx
        state: started
        enabled: true
      
  
